-- -----------------------------------------------------
-- Schema DW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "DW";
SET search_path TO "DW";

-- -----------------------------------------------------
-- Table DimCliente
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DimCliente (
  Cliente_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nome VARCHAR(45) NOT NULL,
  Email VARCHAR(45) NOT NULL,
  Data_Nascimento DATE NOT NULL,
  NIF INT NOT NULL,
  Genero VARCHAR(15) NOT NULL,
  Distrito VARCHAR(45) NOT NULL
);

-- -----------------------------------------------------
-- Table DimProduto
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DimProduto (
  Produto_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nome VARCHAR(45) NOT NULL,
  Marca VARCHAR(45) NOT NULL,
  Categoria VARCHAR(45) NOT NULL,
  Subcategoria VARCHAR(45) NOT NULL,
  Preco DECIMAL(19,2) NOT NULL
);

-- -----------------------------------------------------
-- Table DimCalendario
-- -----------------------------------------------------
-- Usually, in a Calendar dimension, the Date itself is the ID 
-- and is provided manually, but I've kept it as a standard PK.
CREATE TABLE IF NOT EXISTS DimCalendario (
  Data DATE PRIMARY KEY,
  Dia_Semana VARCHAR(45) NOT NULL,
  Semana INT NOT NULL,
  Mes INT NOT NULL,
  Trimestre INT NOT NULL,
  Ano INT NOT NULL
);

-- -----------------------------------------------------
-- Table DimZona
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DimZona (
  Zona_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nome VARCHAR(45) NOT NULL,
  Distrito VARCHAR(45) NOT NULL
);

-- -----------------------------------------------------
-- Table DimFeedback
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DimFeedback (
  Feedback_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Top3Termos VARCHAR(45) NOT NULL,
  Top3Emocoes VARCHAR(45) NOT NULL
);

-- -----------------------------------------------------
-- Table TFVendas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TFVendas (
  Venda_ID INT GENERATED BY DEFAULT AS IDENTITY, -- Internal ID for the sale
  Produto_ID INT NOT NULL,
  Cliente_ID INT NOT NULL,
  Data DATE NOT NULL,
  Zona_ID INT NOT NULL,
  Fonte_ID INT NOT NULL,
  Quantidade INT NOT NULL,
  PrecoUnitario DECIMAL(19,2) NOT NULL,
  -- Composite Primary Key
  PRIMARY KEY (Venda_ID, Produto_ID, Cliente_ID, Data, Zona_ID, Fonte_ID),
  CONSTRAINT ClienteFK1 FOREIGN KEY (Cliente_ID) REFERENCES DimCliente (Cliente_ID),
  CONSTRAINT ProdutoFK1 FOREIGN KEY (Produto_ID) REFERENCES DimProduto (Produto_ID),
  CONSTRAINT CalendarioFK1 FOREIGN KEY (Data) REFERENCES DimCalendario (Data),
  CONSTRAINT ZonaFK1 FOREIGN KEY (Zona_ID) REFERENCES DimZona (Zona_ID)
);

-- -----------------------------------------------------
-- Table TFReviews
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TFReviews (
  Produto_ID INT NOT NULL,
  Cliente_ID INT NOT NULL,
  Data DATE NOT NULL,
  Zona_ID INT NOT NULL,
  Feedback_ID INT NOT NULL,
  Polaridade DECIMAL(8,2) NOT NULL,
  Estrelas INT NOT NULL,
  PRIMARY KEY (Produto_ID, Cliente_ID, Data, Zona_ID, Feedback_ID),
  CONSTRAINT ProdutoFK_R FOREIGN KEY (Produto_ID) REFERENCES DimProduto (Produto_ID),
  CONSTRAINT ClienteFK_R FOREIGN KEY (Cliente_ID) REFERENCES DimCliente (Cliente_ID),
  CONSTRAINT CalendarioFK_R FOREIGN KEY (Data) REFERENCES DimCalendario (Data),
  CONSTRAINT ZonaFK_R FOREIGN KEY (Zona_ID) REFERENCES DimZona (Zona_ID),
  CONSTRAINT FeedbackFK_R FOREIGN KEY (Feedback_ID) REFERENCES DimFeedback (Feedback_ID)
);

-- -----------------------------------------------------
-- Table DimClienteHistorico
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DimClienteHistorico (
  Cliente_ID INT NOT NULL,
  Data_inicio DATE NOT NULL,
  Data_fim DATE NOT NULL,
  Distrito VARCHAR(45) NOT NULL,
  PRIMARY KEY (Cliente_ID, Data_inicio, Data_fim),
  CONSTRAINT FKCliente01 FOREIGN KEY (Cliente_ID) REFERENCES DimCliente (Cliente_ID)
);