version: "3.9"

services:
  postgres_source:
    image: postgres:15
    container_name: relacional
    environment:
      POSTGRES_DB: relacional
      POSTGRES_USER: relacional
      POSTGRES_PASSWORD: relacional
    ports:
      - "5434:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./popular.sql:/docker-entrypoint-initdb.d/02_popular.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres_source


volumes:
  postgres_data:
