SET search_path TO db;
-- ======================
-- Schema
-- ======================
CREATE SCHEMA IF NOT EXISTS db;
SET search_path TO db;

-- ======================
-- Table: clientes
-- ======================
CREATE TABLE clientes (
    cliente_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    nif VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    genero VARCHAR(50) NOT NULL,
    concelho VARCHAR(45),
    distrito VARCHAR(45)
);

-- ======================
-- Table: produtos
-- ======================
CREATE TABLE produtos (
    produto_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_nome VARCHAR(255) NOT NULL,
    marca VARCHAR(100),
    produto_categoria VARCHAR(100),
    produto_subcategoria VARCHAR(100),
    produto_preco DECIMAL(10,2) NOT NULL
);

-- ======================
-- Table: vendas
-- ======================
CREATE TABLE vendas (
    venda_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda DATE NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    cliente_id INT NOT NULL,
    CONSTRAINT fk_cliente_id
        FOREIGN KEY (cliente_id)
        REFERENCES clientes (cliente_id)
);

-- ======================
-- Table: venda_produto
-- ======================
CREATE TABLE venda_produto (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id INT NOT NULL,
    produto_id INT NOT NULL,
    CONSTRAINT fk_vp_venda
        FOREIGN KEY (venda_id)
        REFERENCES vendas (venda_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_vp_produto
        FOREIGN KEY (produto_id)
        REFERENCES produtos (produto_id)
        ON DELETE CASCADE
);
